name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: fwoar-greenhouse
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Run a multi-line script
        run: |
          nix build --json .\#texpkgs \
          | jq -r '.[].outputs | to_entries[].value' \
          | cachix push fwoar-greenhouse

          nix build --print-build-logs

      - uses: actions/upload-artifact@v3
        with:
          name: sample.pdf
          path: result/sample.pdf
          if-no-files-found: error
